server:
  port: 7008
spring:
  #redis配置
  redis:
    host:
    port: 6379
    password:
    database: 0    #Redis数据库索引（默认为0）
  #指定SpringSession用Redis存储实现
  session:
    store-type：redis


#调整日志等级，将需要的操作日志以debug模式输出
logging:
  level:
    com.yan: debug   #可以指定要输出日志的包名和日志等级，该包下的操作会输出debug日志

#feign超时时间
feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000